name: python-exercises
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - scipy
  - matplotlib
  - pandas
  - statsmodels
  - scikit-learn
  - dvc
  - pytest
  - flake8
  - pandoc
  - pip
  - pip:
    - psycopg2-binary
